import = [
  "/home/fred/.npm/_npx/808b709e6234a442/node_modules/alacritty-themes/themes/Ubuntu.toml"
]

[shell]
program = "/bin/zsh"
args = ["--login"]

[[keyboard.bindings]]
chars = "\u001b[67;5u"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001b[86;5u"
key = "V"
mods = "Control|Shift"

[window]
dimensions = { columns = 80, lines = 24 }